# netlify.toml
[build]
  publish = "site"                 # only your public files here
  functions = "netlify/functions"  # serverless functions live here

[functions]
  node_bundler = "esbuild"         # keeps function bundles small

